### ISSUE TITLE
Required Node versions

### ISSUE THREAD

**Issue by k-capehart** [Lightning-Flow-Scanner/lightning-flow-scanner-core#104]
Is there any reason why this repo specifies `node: ^18 || ^20`?

https://github.com/Lightning-Flow-Scanner/lightning-flow-scanner-core/blob/dec28a02b8a316c3f77f8f29f978e47432444837/package.json#L7

Since I have v22.1.0 of node installed on my machine, I get this warning whenever I install the cli tool.

```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'lightning-flow-scanner-core@3.18.0',
npm warn EBADENGINE   required: { node: '^18 || ^20' },
npm warn EBADENGINE   current: { node: 'v22.1.0', npm: '10.8.1' }
npm warn EBADENGINE }
```

**Comment by junners** [comment]
Hey Kyle, yeah there is actually, the current "active" version of node is node 20, and 18 is in maintenance mode to ensure full coverage of active devices.

By Jan 2025, node 22 will be the active version and by that time we should also support ^18 || ^20 || ^22.

More info on https://nodejs.org/en/about/previous-releases

We can absolutely be ahead of this timeline of Jan 2025

**Comment by k-capehart** [comment]
Ah that makes perfect sense. Thanks for the education on the versions, I did not know they rolled them out that way!

**Comment by junners** [comment]
Alrighty~ we could opt in to node 22 early, it doesn't hurt to be ahead of the curve too. However closing this issue for now
