### ISSUE TITLE
Missing Fault Path Rule | False positive on Fast Field Updates Flow for 'Update Records' element

### ISSUE THREAD

**Issue by coluccigiovanni16** [Lightning-Flow-Scanner/lightning-flow-scanner-core#134]
There is the Salesforce limitation: adding a Fault Path in the “Update Records” element of Flow optimized for Fast Field Updates is impossible.
I already found a possible way to fix it:
```
 // Find the start element to check its trigger type
    const startElement = flow.elements.find((el) => el.type === "start");
    const elementsWhereFaultPathIsApplicable = (
      flow.elements.filter(
        (node) =>
          node instanceof core.FlowNode &&
          [
            "recordLookups",
            "recordDeletes",
            "recordUpdates", // We are particularly interested in this
            "recordCreates",
            "waits",
            "actionCalls",
          ].includes(node.subtype)
      ) as core.FlowNode[]
    ).map((e) => e.name);

    const visitCallback = (element: core.FlowNode) => {
      // Avoid adding to the error list for recordUpdates if the flow is RecordBeforeSave
      if (element.subtype === "recordUpdates" && startElement?.triggerType === "RecordBeforeSave") {
        return; // Skip adding this to the error list but continue processing
      }
```

To be replaced in the file lightning-flow-scanner-core/src/main/rules/MissingFaultPath.ts from line 26 to 41.

Here is the Flow screenshot with faulty element.
[iScreen Shoter - 20241023102605020.pdf](https://github.com/user-attachments/files/17487629/iScreen.Shoter.-.20241023102605020.pdf)

**Comment by junners** [comment]
Hi @coluccigiovanni16 for taking interest in using lightning flow scanner! Appreciate your contribution!

Lemme wrap my head around what's happening here. On your fast update flow, are you then looking to update the same record that initiated the flow? 

A general rule of thumb is you do cross object updates on an "after" event for you to make sure all logic for the initial object has been ran i.e if you have a flow from account that also propagates information to contact, you update the contact on an after event instead of before.
And if you do try and update the same record that initiated the flow, then it should be a variable assignment in a fast update flow instead of an update element.

**Comment by coluccigiovanni16** [comment]
Hi @junners, 
totally agree on you.
The error comes out while we where deeply testing the scenario covered by the tool(that is really great!!!).
So, answering to your question  '_On your fast update flow, are you then looking to update the same record that initiated the flow?_' --> Yes, we want to update the same record that initiated the flow. About the flow that trigger the issue, we are using the 'Assignment' element(update element was used to test some tools scenarios). Thanks

**Comment by junners** [comment]
Mmmm i see, lemme try and translate this to a rule and please let me know your thoughts on this.

- on fast update flows, there should be no update elements on the record that triggered the flow
- on fast update flows, update elements (incase somebody uses it) should bypass the missing fault path that you specified above.

Would this be an accurate and inclusive statement?

**Comment by coluccigiovanni16** [comment]
Hi @junners,
I would say 'Yes'.

**Comment by junners** [comment]
Fixes on "on fast update flows, update elements (incase somebody uses it) should bypass the missing fault path that you specified above." will be in the latest version. I'm currently creating a new rule called "PreferVariableAssignmentOnBeforeUpdate". The new rule will be in beta/opt-in for a few releases

**Comment by junners** [comment]
TBD on the new name. it's long haha
