### ISSUE TITLE
New Rule: check if flow is saved in auto layout

### ISSUE THREAD

**Issue by fkramer690** [Lightning-Flow-Scanner/lightning-flow-scanner-core#32]
Sometimes a record-triggered flow is not showing in the trigger explorer if it is not saved in the auto layout mode. Apart from that, there are more benefits to do so. 

I assume for you it is an easy one to check the tag and return true / false

    <processMetadataValues>
        <name>CanvasMode</name>
        <value>
            <stringValue>AUTO_LAYOUT_CANVAS</stringValue>
        </value>
    </processMetadataValues>

**Comment by fkramer690** [comment]
This feature seems to be in beta, but at least that is my recommendation. The auto layout will give you a tree-like representation of the flow and makes it easier to understand the logic from top to button. apart from that, Salesforce does not let you create unconnected elements. 

https://help.salesforce.com/s/articleView?id=release-notes.rn_forcecom_flow_fbuilder_autolayout_mode.htm&release=228&type=5


  <stringValue>FREE_FORM_CANVAS</stringValue> is the value which should not be used  <stringValue>AUTO_LAYOUT_CANVAS</stringValue> is the correct one

Below you will see that sometimes record-triggered flows are not showing up in the flow trigger explorer if saved in free form. Saving the flow in an auto-save layout will fix the issue. Since this is only appearing for record triggered flows, this can may be filtered to flows with 


    <start>
        <locationX></locationX>
        <locationY></locationY>
        <connector>
            <targetReference>Flow_enabled</targetReference>
        </connector>
        <object></object>
        **<recordTriggerType>CreateAndUpdate</recordTriggerType>**
        <triggerType></triggerType>
    </start>

<img width="871" alt="image" src="https://github.com/Force-Config-Control/lightning-flow-scanner-core/assets/87364496/0c91533e-0340-49d2-9a77-5a46539fc265">

<img width="761" alt="image" src="https://github.com/Force-Config-Control/lightning-flow-scanner-core/assets/87364496/a3d40a4a-963b-49a8-9c8c-1053d8acbc7f">

**Comment by RubenHalman** [comment]
To be honest, I agree and this is an easy rule, but it also makes me think we ideally need 'Beta' rules. My proposal would be that this becomes an included best practice as soon as  the feature is not in beta anymore?
