### ISSUE TITLE
All Node in a Schedule Path fails Unconnected Elements Rule

### ISSUE THREAD

**Issue by indiankira4287** [Lightning-Flow-Scanner/lightning-flow-scanner-core#48]
Hi, 
I have scanned a flow with a scheduled path and all the elements in the scheduled path are getting marked as violations for Unconnected Elements. 
This issue doesn't exist for other flow types.

**Comment by RubenHalman** [comment]
@indiankira4287  I am sorry for this late reply. My suspicion is that it could be due to the fact that the particular flow is using unsupported flow elements?

**Comment by Anton-Solomin-Checkatrade** [comment]
It looks like it's still an issue in asynchronous paths

**Comment by junners** [comment]
Hey @Anton-Solomin-Checkatrade could you please provide a sample flow?

**Comment by Anton-Solomin-Checkatrade** [comment]
@junners 

`<?xml version="1.0" encoding="UTF-8"?>
<Flow xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionCalls>
        <name>Send_RVM_warning_EMAIL</name>
        <label>Send RVM warning EMAIL</label>
        <locationX>242</locationX>
        <locationY>384</locationY>
        <actionName>Account.RVM_warning_email_for_strategic_accounts</actionName>
        <actionType>emailAlert</actionType>
        <flowTransactionModel>CurrentTransaction</flowTransactionModel>
        <inputParameters>
            <name>SObjectRowId</name>
            <value>
                <elementReference>$Record.Id</elementReference>
            </value>
        </inputParameters>
        <nameSegment>Account.RVM_warning_email_for_strategic_accounts</nameSegment>
        <versionSegment>1</versionSegment>
    </actionCalls>
    <apiVersion>61.0</apiVersion>
    <decisions>
        <name>is_Business_Development_Manager</name>
        <label>is Owner Title &apos;Business Development Manager&apos;?</label>
        <locationX>374</locationX>
        <locationY>276</locationY>
        <defaultConnectorLabel>No</defaultConnectorLabel>
        <rules>
            <name>Yes_is_bdm</name>
            <conditionLogic>and</conditionLogic>
            <conditions>
                <leftValueReference>$Record.Owner.Title</leftValueReference>
                <operator>EqualTo</operator>
                <rightValue>
                    <stringValue>Business Development Manager</stringValue>
                </rightValue>
            </conditions>
            <connector>
                <targetReference>Send_RVM_warning_EMAIL</targetReference>
            </connector>
            <label>Yes</label>
        </rules>
    </decisions>
    <description>RVM warning email for strategic accounts</description>
    <environments>Default</environments>
    <interviewLabel>RVM warning email for strategic accounts {!$Flow.CurrentDateTime}</interviewLabel>
    <label>RVM warning email for strategic accounts</label>
    <processMetadataValues>
        <name>BuilderType</name>
        <value>
            <stringValue>LightningFlowBuilder</stringValue>
        </value>
    </processMetadataValues>
    <processMetadataValues>
        <name>CanvasMode</name>
        <value>
            <stringValue>AUTO_LAYOUT_CANVAS</stringValue>
        </value>
    </processMetadataValues>
    <processMetadataValues>
        <name>OriginBuilderType</name>
        <value>
            <stringValue>LightningFlowBuilder</stringValue>
        </value>
    </processMetadataValues>
    <processType>AutoLaunchedFlow</processType>
    <start>
        <locationX>50</locationX>
        <locationY>0</locationY>
        <filterLogic>and</filterLogic>
        <filters>
            <field>Status__c</field>
            <operator>EqualTo</operator>
            <value>
                <stringValue>RVM</stringValue>
            </value>
        </filters>
        <filters>
            <field>Status__c</field>
            <operator>IsChanged</operator>
            <value>
                <booleanValue>true</booleanValue>
            </value>
        </filters>
        <object>Account</object>
        <recordTriggerType>Update</recordTriggerType>
        <scheduledPaths>
            <connector>
                <targetReference>is_Business_Development_Manager</targetReference>
            </connector>
            <pathType>AsyncAfterCommit</pathType>
        </scheduledPaths>
        <triggerType>RecordAfterSave</triggerType>
    </start>
    <status>Active</status>
</Flow>
`

**Comment by junners** [comment]
@Anton-Solomin-Checkatrade - hey there! Thanks for waiting. I just tried this on the latest and it works. Are you perhaps running on an old version? 
You can check on your running version using `sf plugins` The latest version would be 2.34
