### ISSUE TITLE
DML Inside Loop with Screen

### ISSUE THREAD

**Issue by alecdorner** [Lightning-Flow-Scanner/lightning-flow-scanner-core#61]
I noticed the lightning flow scanner will flag DML elements inside a loop if a screen element is also in that same loop. While it is technically DML inside a loop, the screen element splits up the transactions between each loop, thus neutralizing the concerns around governor limits. It might make sense to consider whether a screen is between the element and the path looping back around since this may be considered a false positive in most cases.

**Comment by RubenHalman** [comment]
I have resolved this issue by excluding visual flows from the SOQL/DML statement in loop rules in 2.30. Thank you for your input, it will soon be included in the sfdx and vsce solutions!

**Comment by RubenHalman** [comment]
I have resolved this issue by excluding visual flows from the SOQL/DML statement in loop rules in 2.30. Thank you for your input, it will soon be included in the sfdx and vsce solutions!
